version: "3.3"

services:
  nodeserver:
    build:
      context: ./app
    ports:
        - 3000:3000
  reverse_proxy:
    restart: always
    ports:
      - 80:80
    build:
      context: ./nginx
      